# Dr. Toribio Example

### Load Packages

In [1]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from numpy import mean
from numpy import std
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

### Read in Data

2010 data. Last 10 average.

In [6]:
os.chdir('/Users/johnoliver/Downloads/grad-nba-wins/data/mod_data')
# data from 2010
df10 = pd.read_csv("mod10.csv")
# get rid of first variable (unique identifier)
df10 = df10.iloc[:,1:]

### Format Data

In [7]:
# define x and y variables
feature_cols = ["h_avg_points","a_avg_points","h_avg_fg","a_avg_fg",
                "h_avg_fga","a_avg_fga","h_avg_3p","a_avg_3p",
                "h_avg_3pa","a_avg_3pa","h_avg_ft","a_avg_ft",
                "h_avg_orb","a_avg_orb","h_avg_drb" ,"a_avg_drb",
                "h_avg_ast","a_avg_ast","h_avg_stl", "a_avg_stl", 
                "h_avg_blk","a_avg_blk","h_avg_tov","a_avg_tov",
                "h_avg_pf","a_avg_pf" ,"h_avg_tsp",  "a_avg_tsp",
                "h_avg_ortg","a_avg_ortg","h_avg_drtg","a_avg_drtg",
                "h_win_perc","a_win_perc","h_back","a_back",
                "home_elo", "away_elo"]

X = df10[feature_cols]
Y = df10.win_status

scaler = StandardScaler()
scale_X = scaler.fit_transform(X)

# split data into training and testing
X_train,X_test,y_train,y_test=train_test_split(X,Y,
                                               test_size=0.3,
                                               random_state=0)
# scaled data
scale_X_train,scale_X_test,y_train,y_test=train_test_split(scale_X,Y,
                                               test_size=0.3,
                                               random_state=0)


## Unparameterized

In [ ]:
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats = 1,
                             random_state=1)

lr_model = LogisticRegression()
lr_scores = cross_val_score(lr_model, X, Y,
                            scoring = 'accuracy', cv = cv,
                            n_jobs = 1)

In [17]:
# scores for the 10 folds
lr_scores

array([0.645     , 0.71      , 0.745     , 0.70351759, 0.66331658])

In [ ]:
lr_model2 = LogisticRegression(C = 1)
lr_scores2 = cross_val_score(lr_model2, X, Y,
                            scoring = 'accuracy', cv = cv,
                            n_jobs = 1)

lr_model3 = LogisticRegression(C = 10)
lr_scores3 = cross_val_score(lr_model3, X, Y,
                            scoring = 'accuracy', cv = cv,
                            n_jobs = 1)

lr_model4 = LogisticRegression(C = 50)
lr_scores4 = cross_val_score(lr_model4, X, Y,
                            scoring = 'accuracy', cv = cv,
                            n_jobs = 1)

In [20]:
lr_scores2

array([0.63      , 0.715     , 0.745     , 0.71356784, 0.66834171])

In [23]:
lr_scores3

array([0.635     , 0.715     , 0.745     , 0.69849246, 0.65326633])

In [24]:
lr_scores4

array([0.63      , 0.715     , 0.745     , 0.71356784, 0.66834171])